# Generated by Django 4.2.4 on 2023-09-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='piso',
            field=models.CharField(blank=True, max_length=5, verbose_name='Piso:'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='sigla',
            field=models.CharField(max_length=30, verbose_name='Sigla:'),
        ),
    ]
