# Generated by Django 4.2.4 on 2023-09-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_piso_alter_departamento_sigla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Areas', 'verbose_name_plural': 'Áreas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'sigla')},
        ),
    ]
