# Generated by Django 4.2.4 on 2023-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=30, verbose_name='Nombre de la empresa:')),
                ('sigla', models.CharField(max_length=30, verbose_name='Sigla:')),
                ('activo', models.BooleanField(default=False, verbose_name='Esta activo?:')),
                ('direccion', models.CharField(blank=True, max_length=5, verbose_name='Dirección:')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono:')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores de la empresa',
                'ordering': ['nombre_empresa'],
                'unique_together': {('nombre_empresa', 'sigla')},
            },
        ),
    ]
