# Generated by Django 4.2.4 on 2023-09-24 12:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
