# Generated by Django 4.2.4 on 2023-10-07 18:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=60, verbose_name='Producto')),
                ('Tipo_prod', models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRATIVO'), ('2', 'DESARROLLADOR'), ('3', 'ANALISTA FUNCIONAL'), ('4', 'OTRO')], max_length=1, verbose_name='Tipo de producto')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['producto'],
            },
        ),
    ]
