# Generated by Django 4.2.4 on 2023-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Autor',
            field=models.CharField(blank=True, max_length=60, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='año',
            field=models.CharField(blank=True, max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=60, unique=int, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='editorial',
            field=models.CharField(blank=True, max_length=60, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(blank=True, max_length=60, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Tipo_prod',
            field=models.CharField(choices=[('0', 'LIBRO'), ('1', 'PAPELERIA')], max_length=1, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(blank=True, max_length=60, verbose_name='Producto'),
        ),
    ]
