# Generated by Django 4.2.4 on 2023-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_autor_producto_año_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='año',
            field=models.CharField(blank=True, choices=[('0', '2000'), ('1', '2001'), ('2', '2002'), ('03', '2003'), ('4', '2004'), ('5', '2005'), ('6', '2006'), ('07', '2007')], max_length=4, verbose_name='Año'),
        ),
    ]
