# Generated by Django 4.2.4 on 2023-10-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_habilidades_producto_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Habilidades',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
