# Generated by Django 4.2.4 on 2023-10-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_habilidades_delete_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='editorial',
        ),
    ]
