# Generated by Django 4.2.4 on 2023-10-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_remove_proveedor_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='editorial',
            field=models.BooleanField(default=False, verbose_name='Es una editorial?:'),
        ),
    ]
