# Generated by Django 4.2.4 on 2023-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_proveedor_editorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=60, verbose_name='Proveedor'),
        ),
    ]
