# Generated by Django 4.2.4 on 2023-10-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('productos', '0013_remove_producto_proveedor_delete_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='codigo_producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
